# See https://docs.neoforged.net/docs/1.21.11/gettingstarted/modfiles/
modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="openwheelracing"
version="1.15.4"
displayName="Openwheel Racing"
authors="Pilot Raikonnen"
description='''
Craft, tune, and race open-wheel cars on custom-built Minecraft circuits.
'''

[[mixins]]
    config="openwheelracing.mixins.json"

[[dependencies.openwheelracing]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.11,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.openwheelracing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.11,1.22,)"
    ordering="NONE"
    side="BOTH"
